bank_app/urls.py
from django.urls import path
from .api import AccountList, CustomerAccounts
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('accounts/', views.accounts, name='accounts'),
    path('transfer_money/', views.transfer_money, name='transfer_money'),
    path('loans/', views.loans, name='loans'),
    path('download_pdf/<int:account_id>', views.download_pdf, name='download_pdf'),
    path('api/v1/', AccountList.as_view()),
    path('api/v1/<int:pk>', CustomerAccounts.as_view()),
    # Paths for bankers
    path('all_customers/', views.all_customers, name='all_customers'),
    path('new_customer/', views.new_customer, name='new_customer'),
    path('customer_details/<int:customer_id>', views.customer_details, name='customer_details'),
    path('create_customer_account/<int:customer_id>', views.create_customer_account, name='create_customer_account'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
    path('invest_app/', include('invest_app.urls')),
]

invest_app/urls.py
from django.urls import path
from . import views

app_name = 'invest_app'

urlpatterns = [
    path('investments/', views.investments, name="investments"),
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
]

bank_app/models.py
from django.db import models, transaction
from django.contrib.auth.models import User, Group
from decimal import Decimal
from uuid import uuid4
from bank_project import settings
from .errors import InsufficientFunds


class CustomerRank(models.Model):
    name = models.CharField(max_length=35, unique=True)
    value = models.IntegerField(unique=True)

    @classmethod
    def default_rank(cls):
        min_rank = cls.objects.all().aggregate(
            models.Min('value'))['value__min']
        return cls.objects.get(value=min_rank)

    def __str__(self):
        return f'{self.name} - {self.value}'


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    rank = models.ForeignKey(CustomerRank, on_delete=models.PROTECT)
    phone = models.CharField(max_length=35)

    @classmethod
    def create_customer(cls, username, password, email, phone, rank=CustomerRank.default_rank()):
        user = User.objects.create_user(
            username=username, email=email, password=password)
        customer = cls()
        customer.user = user
        customer.rank = rank
        customer.phone = phone
        customer.save()

        # Automatically add user to Customer group
        group = Group.objects.get(name='Customer')
        user.groups.add(group)

        # Create starter account for new customer.
        Account(user=user, name='Starter account').save()
        return user

    def update_user(self, username, email, phone):
        self.user.username = username
        self.user.email = email
        self.user.save()

        self.phone = phone
        self.save()

    @property
    def accounts(self):
        return Account.objects.filter(user=self.user)

    @property
    def can_make_loans(self):
        return self.rank.value >= settings.MINIMUM_RANK_LOAN

    def make_loan(self, amount, loan_name, selected_account):
        if self.can_make_loans:
            loan = Account(user=self.user, name=loan_name)
            loan.save()
            to_account = Account.objects.get(
                user=self.user, name=selected_account)
            Transaction.transfer(loan, to_account, Decimal(amount), is_loan=True)

    def __str__(self):
        return f'{self.user} - {self.rank}'


class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=35)

    @classmethod
    def create_account(cls, user, name):
        account = cls()
        account.user = user
        account.name = name
        account.save()

    @property
    def balance(self):
        return Transaction.objects.filter(account=self).aggregate(models.Sum('amount'))['amount__sum'] or Decimal('0')

    @property
    def movements(self):

        return Transaction.objects.filter(account=self)

    def __str__(self):
        return f'{self.user} - {self.name}'


class Transaction(models.Model):
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    transaction_id = models.CharField(max_length=35)
    amount = models.DecimalField(max_digits=18, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=35)

    @classmethod
    def transfer(cls, from_account, to_account, amount, is_loan=False):
        with transaction.atomic():
            if from_account.balance >= amount or is_loan:
                transaction_id = str(uuid4())
                cls(account=from_account, transaction_id=transaction_id,
                    amount=-amount, text=f"""Transaction: Credit
                    From: {from_account}
                    To: {to_account}
                    """).save()
                cls(account=to_account, transaction_id=transaction_id,
                    amount=amount, text=f"""Transaction: Debit
                    From: {to_account}
                    To: {from_account}
                    """).save()
            else:
                raise InsufficientFunds

    def __str__(self):
        return f'{self.amount} - {self.transaction_id}'

bank_app/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from decimal import Decimal
from .models import CustomerRank, Customer, Account, Transaction
from .utils import group_required
from .pdf import create_pdf
import django_rq
from django.core.files import File


@login_required
def index(request):
    return render(request, 'bank_app/index.html')


@login_required
def profile(request):
    if request.method == 'POST':
        customer_id = request.user.customer.id
        username = request.POST['username']
        email = request.POST['email']
        phone = request.POST['phone']
        customer = get_object_or_404(Customer, id=customer_id)
        customer.update_user(username, email, phone)
        return HttpResponseRedirect(reverse('bank_app:profile'))
    context = {
        'user': request.user
    }
    return render(request, 'bank_app/profile.html', context)


@group_required('Banker')
def new_customer(request):
    if request.method == 'POST':
        # Get form information
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        phone = request.POST['phone']
        if password == confirm_password:
            # create Customer - User is made inside of the classmethod "create_customer"
            Customer.create_customer(username, password, email, phone)
            return HttpResponseRedirect(reverse('bank_app:all_customers'))
    else:
        return render(request, 'bank_app/new_customer.html')


@group_required('Banker')
def all_customers(request):
    customers = Customer.objects.all()
    context = {
        'customers': customers
    }
    return render(request, 'bank_app/all_customers.html', context)


@group_required('Banker')
def customer_details(request, customer_id):
    customer = get_object_or_404(Customer, id=customer_id)
    customer_ranks = CustomerRank.objects.all()

    context = {
        'customer': customer,
        'customer_ranks': customer_ranks,
    }
    if request.method == "POST":
        rank = request.POST['rank']
        customer.rank = get_object_or_404(CustomerRank, value=rank)
        username = request.POST['username']
        email = request.POST['email']
        phone = request.POST['phone']
        customer.update_user(username, email, phone)

    return render(request, 'bank_app/customer_details.html', context)


@login_required
def accounts(request):
    customer = get_object_or_404(Customer, id=request.user.customer.id)
    django_rq.enqueue(create_pdf, {
        'customer': customer
    })
    context = {
        'customer': customer
    }
    return render(request, 'bank_app/accounts.html', context)


@group_required('Banker')
def create_customer_account(request, customer_id):
    context = {
        'customer_id': customer_id
    }
    if request.method == "POST":
        customer = get_object_or_404(Customer, id=customer_id)
        user = customer.user
        name = request.POST['name']
        Account.create_account(user, name)
        return HttpResponseRedirect(reverse('bank_app:customer_details', args=[customer_id]))
    else:
        return render(request, 'bank_app/create_customer_account.html', context)


@login_required
def transfer_money(request):
    if request.method == 'POST':
        from_account = get_object_or_404(Account, pk=request.POST['from_account'])
        to_account = get_object_or_404(Account, pk=request.POST['to_account'])
        amount = Decimal(request.POST['amount'])
        Transaction.transfer(from_account, to_account, amount)
        return HttpResponseRedirect(reverse('bank_app:accounts'))
    else:
        user_accounts = request.user.customer.accounts
        all_customers = Customer.objects.all()
        context = {
            'user_accounts': user_accounts,
            'all_customers': all_customers,
        }
        return render(request, 'bank_app/transfer_money.html', context)


@login_required
def loans(request):
    customer = get_object_or_404(Customer, id=request.user.customer.id)
    if request.method == 'POST':
        loan_name = request.POST['loan_name']
        selected_account = request.POST['account_name']
        amount = request.POST['amount']
        customer.make_loan(amount, loan_name, selected_account)
        return HttpResponseRedirect(reverse('bank_app:accounts'))
    else:
        context = {
            'customer': customer
        }
        return render(request, 'bank_app/loans.html', context)


def download_pdf(request, account_id):
    user = request.user
    path_to_file = f'files/{user}-account-{account_id}.pdf'
    f = open(path_to_file, 'rb')
    myfile = File(f)
    response = HttpResponse(myfile, content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename='f'{user}-account-{account_id}.pdf'
    return response

bank_app/templates/bank_app/accounts.html
{% extends 'bank_app/base.html' %}
{% block title %} Accounts {% endblock %}

{% block content %}
<h1>My accounts</h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Balance</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for account in customer.accounts %}
        <tr>
            <td>{{account.id}}</td>
            <td>{{account.name}}</td>
            <td>{{account.balance}}</td>
            <td><a href="#accountTransactions-{{account.id}}" data-toggle="collapse" aria-expanded="false" aria-controls="accountTransactions-{{account.id}}">View transactions</a></td>
            <td><a href="{% url 'bank_app:download_pdf' account.id %}">Download PDF</a></td>
        </tr>
        <tr class="collapse bg-light" id="collapseMe">
            <th scope="col">Account</th>
            <th scope="col">Amount</th>
            <th scope="col">Text</th>
            <th></th>
            <th></th>
        </tr>
        {% for movement in account.movements %}
        <tr class="collapse bg-light" id="accountTransactions-{{account.id}}">
            <td>
                {{movement.account}}
            </td>
            <td>
                {{movement.amount}}
            </td>
            <td>
                {{movement.text}}
            </td>
            <td></td>
            <td></td>
        </tr>
        {% endfor %}
        
    {% endfor %}
</table>

{% endblock %}

bank_app/templates/bank_app/all_customers.html
{% extends 'bank_app/base.html' %}
{% block title %} All customers {% endblock %}

{% block content %}
<h1>All customers</h1>
<hr>
<form action="">
    <label for="name">Name</label>
    <input id="searchTerm" type="text" name="name" autocomplete="off">
</form>
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Username</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Rank</th>
            <th scope="col">Details</th>
        </tr>
    </thead>
    <tbody id="">
    {% for customer in customers %}
        <tr>
            <th scope="row">{{ customer.id }}</th>
            <td>{{ customer.user.username }}</td>
            <td>{{ customer.user.email }}</td>
            <td>{{ customer.phone }}</td>
            <td>{{ customer.rank }}</td>
            <td><a href="{% url 'bank_app:customer_details' customer.id %}">Details</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
{% block javascript %}
<script>
    $("#searchTerm").keyup(function () {
        var searchTerm = $("#searchTerm").val().toLowerCase();
        $("tbody tr").filter(function () {
            $(this).toggle($(this).text().toLowerCase().indexOf(searchTerm) > -1)
        });
    });
</script>
{% endblock %}

bank_app/templates/bank_app/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% load has_group %}
</head>

<body>

    <nav class="navbar bg-dark navbar-dark navbar-expand-md">
        <a class="navbar-brand" href="{% url 'bank_app:index' %}">Home</a>
        <div class="collapse navbar-collapse" id="navbarCollapse"></div>
        <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
            {% if request.user|has_group:"Banker" %}
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'bank_app:new_customer' %}">New customer</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'bank_app:all_customers' %}">All customers</a></li>
            {% elif request.user|has_group:"Customer" %}
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'invest_app:investments' %}">Investments</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'bank_app:loans' %}">Make a loan</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'bank_app:accounts' %}">Accounts</a></li>
                <li class="nav-item"><a class="nav-link text-white" href="{% url 'bank_app:transfer_money' %}">Transfer</a></li>
            {% endif %}
            <li class="nav-item"><a class="nav-link text-white" href="{% url 'bank_app:profile' %}">Profile</a></li>
            <li class="nav-item"><a class="nav-link text-white" href="{% url 'login_app:logout' %}">Logout</a></li>
        {% else %}
            <li class="nav-item"><a class="nav-link text-white" href="{% url 'login_app:login' %}">Login</a></li>
        {% endif %}
        </ul>
    </nav>

    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    {% block javascript %}{% endblock %}

</body>

</html>

bank_app/templates/bank_app/create_customer_account.html
{% extends 'bank_app/base.html' %}
{% block title %} Customer details {% endblock %}

{% block content %}
<h1>Create new account</h1>
<hr>
<form action="{% url 'bank_app:create_customer_account' customer_id %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input class="form-control" type="text" name="name" placeholder="Name">
            </div>
            <input class="btn btn-primary" type="submit" value="Create account">
        </div>
    </div>
</form>
<hr>
{% endblock %}

bank_app/templates/bank_app/customer_details.html
{% extends 'bank_app/base.html' %}
{% block title %} Customer details {% endblock %}

{% block content %}
<h1>Customer details</h1>
<hr>
<form action="{% url 'bank_app:customer_details' customer.id %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="username">Username:</label>
                <input class="form-control" name="username" type="text" value="{{customer.user.username}}">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input class="form-control" name="email" type="text" value="{{customer.user.email}}">
            </div>
            <div class="form-group">
                <label for="phone">Phone number:</label>
                <input class="form-control" name="phone" type="tel" value="{{customer.phone}}">
            </div>
            <div class="form-group">
                <label for="rank">Rank:</label>
                <select class="form-control" name="rank">
                    {% for rank in customer_ranks %}
                    <option value="{{rank.value}}" {% if customer.rank.value == rank.value %} selected {% endif %}>
                        {{rank.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <input type="submit" class="btn btn-primary" value="Update">
        </div>
    </div>
</form>
<hr>

<div class="col-md-6 bg-light">
    <h2>Accounts:</h2>
    <a href="{% url 'bank_app:create_customer_account' customer.id %}">Create new account for {{customer.user.username}}</a>
    {% for account in customer.accounts %}
    <a class="border-dark border-bottom d-flex justify-content-between text-dark" href="#accountTransactions-{{account.id}}" data-toggle="collapse" aria-expanded="false" aria-controls="accountTransactions">    
        <span class="mr-5">
            {{account.name}}
        </span>
        <span>
            {{account.balance}} &darr;
        </span>
    </a>
    <ul class="list-group collapse" id="accountTransactions-{{account.id}}">
        {% for account_movement in account.movements %}
        <li class="list-group-item">
            <p>Text: {{account_movement.text}}</p>
            <p>Amount: {{account_movement.amount}}</p>
            <p>Timestamp: {{account_movement.timestamp}}</p>
            
        </li>
        {% endfor %}
    </ul>
    {% endfor %}
    
</div>
{% endblock %}

bank_app/templates/bank_app/index.html
{% extends 'bank_app/base.html' %}
{% block title %} Home {% endblock %}

{% block content %}
<h1>Home page</h1>
<h3>Logged in to user: {{user}}</h3>

<h2>Er diagram</h2>
{% load static %}
<img src="{% static 'bank_app/ER-Diagram.jpg' %}" alt="er-diagram" style="width: 70%;">
{% endblock %}

bank_app/templates/bank_app/loans.html
{% extends 'bank_app/base.html' %}
{% block title %} Loans {% endblock %}
{% block content %}
{% if customer.can_make_loans %}
<h1>Make a loan</h1>
<hr>
<form action="{% url 'bank_app:loans' %}" method="POST">
    {% csrf_token %}
    <div class="col-md-4">
        <div class="form-group">
            <input class="form-control" type="number" name="amount" placeholder="Loan amount" autocomplete="off">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="loan_name" placeholder="Name of loan">
        </div>
        <div class="form-group">
            <select name="account_name" class="form-control">
                {% for account in customer.accounts %}
                {% if account.balance >= 0 %}
                <option value="{{account.name}}">{{account.name}}</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>
        <input class="btn btn-primary" type="submit" value="Take loan">
    </div>

</form>
<hr>
{% else %}
<p>You need to be silver or gold member to take a loan :) {{user.userprofile}}</p>
{% endif %}
{% endblock %}

bank_app/templates/bank_app/new_customer.html
{% extends 'bank_app/base.html' %}
{% block title %} New Customer {% endblock %}

{% block content %}
<h1>Create new customer</h1>
<hr>
<form action="{% url 'bank_app:new_customer'%}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input class="form-control" type="text" name="username" placeholder="Customers Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="email" name="email" placeholder="Customers email">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Customers password">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="confirm_password"
                    placeholder="Cornfirm customers password">
            </div>
            <div class="form-group">
                <input class="form-control" type="tel" name="phone" placeholder="Customers telephone number">
            </div>
            <input class="btn btn-primary" type="submit" value="Create customer">
        </div>
    </div>
</form>
<hr>
{% endblock %}

bank_app/templates/bank_app/profile.html
{% extends 'bank_app/base.html' %}
{% block title %} Profile {% endblock %}

{% block content %}
<h1>User info for: {{user.username}}</h1>
<hr>
<form action="{% url 'bank_app:profile'%}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label for="username">Username:</label>
                <input class="form-control" type="text" name="username" value="{{user.username}}">
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input class="form-control" type="email" name="email" value="{{user.email}}">
            </div>
            <div class="form-group">
                <label for="phone">Phone number:</label>
                <input class="form-control" type="tel" name="phone" value={{user.customer.phone}}>
            </div>
            <input class="btn btn-primary" type="submit" value="Save changes">
        </div>
    </div>
</form>
<hr>
<a href="{% url 'login_app:password_reset' %}">Request Password Reset</a>
{% endblock %}

bank_app/templates/bank_app/transfer_money.html
{% extends 'bank_app/base.html' %}
{% block title %} Tranfer money {% endblock %}

{% block content %}
<h1>Transfer money</h1>
<hr>
<form action="{% url 'bank_app:transfer_money' %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                From account:
                <select class="form-control" name="from_account">
                    {% for account in user_accounts %}
                    <option value="{{account.pk}}">{{account}} ({{account.balance}} kr.)</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                To user:
                <select class="form-control" name="customer-pk" id="customer-pk">
                    {% for customer in all_customers %}
                    <option value="{{customer.user.pk}}">{{customer.user.username}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                To account:
                <select class="form-control" id=customerAccounts name="to_account">
                    <option value="" disabled hidden selected>Select account</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input class="form-control" type="number" name="amount" placeholder="Transfer amount"
                    autocomplete="off">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input class="btn btn-primary" type="submit" value="Transfer money">
            </div>
        </div>
    </div>
</form>
<hr>


{% if error %}<p style="color:red;">{{error}}</p>{% endif %}
{% endblock %}
{% block javascript %}
<script>
    $("#customer-pk").change(function () {
        var user_id = $(this).val();
        $.ajax({
            url: `/api/v1/${user_id}`,
            dataType: 'json',
            success: function (data) {
                $("#customerAccounts").empty();
                $("#customerAccounts").append("<option value='' disabled hidden selected>Select account</option>")
                for (i = 0; i < data.length; i++) {
                    $("#customerAccounts").append(`<option value="${data[i].id}">${data[i].name}</option>`);
                }
            }
        });
    });
</script>
{% endblock %}