bank_app/urls.py
from django.urls import path
from .api import AccountList, CustomerAccounts
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('accounts/', views.accounts, name='accounts'),
    path('transfer_money/', views.transfer_money, name='transfer_money'),
    path('loans/', views.loans, name='loans'),
    path('download_pdf/<int:account_id>', views.download_pdf, name='download_pdf'),
    path('api/v1/', AccountList.as_view()),
    path('api/v1/<int:pk>', CustomerAccounts.as_view()),
    # Paths for bankers
    path('all_customers/', views.all_customers, name='all_customers'),
    path('new_customer/', views.new_customer, name='new_customer'),
    path('customer_details/<int:customer_id>', views.customer_details, name='customer_details'),
    path('create_customer_account/<int:customer_id>', views.create_customer_account, name='create_customer_account'),
]

bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bank_app.urls')),
    path('accounts/', include('login_app.urls')),
    path('invest_app/', include('invest_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('password_reset/', views.password_reset, name='password_reset'),
    path('password_reset_secret/<str:secret>/', views.password_reset_secret, name='password_reset_secret'),
    path('password_reset_form/', views.password_reset_form, name='password_reset_form'),
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe


class PasswordResetRequest(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    secret = models.CharField(max_length=43, default=token_urlsafe)
    created_timestamp = models.DateTimeField(auto_now_add=True)
    updated_timestamp = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user} - {self.created_timestamp}"

login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from .import models
import django_rq
from .messaging import email_message


def login(request):
    context = {}
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse("bank_app:index"))
        else:
            context = {"error": "Bad username or password."}

    return render(request, "login_app/login.html", context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse("login_app:login"))


def password_reset(request):
    context = {}

    if request.method == "POST":
        email = request.POST["email"]
        user = User.objects.get(email=email)
        reset_request = models.PasswordResetRequest()
        reset_request.user = user
        reset_request.save()
        url = reverse(
            "login_app:password_reset_secret", args=[f"{reset_request.secret}"]
        )
        url = f'{request.scheme}://{request.META["HTTP_HOST"]}{url}'

        # this print will allow you to change password on "not real" emails
        print(url)
        context = {"message": "Please click the link in the email we sent to your email."}
        django_rq.enqueue(email_message, {"email_receiver": email, "reset_link": url})

    return render(request, "login_app/password_reset.html", context)


def password_reset_secret(request, secret):
    context = {"secret": secret}
    return render(request, "login_app/password_reset_form.html", context)


def password_reset_form(request):
    email = request.POST["email"]
    password = request.POST["password"]
    confirm_password = request.POST["confirm_password"]
    secret = request.POST["secret"]

    user = User.objects.get(email=email)
    reset_request = models.PasswordResetRequest.objects.get(user=user, secret=secret)
    if password == confirm_password:
        user.set_password(password)
        user.save()
        reset_request.save()
        return HttpResponseRedirect(reverse("login_app:login"))
    context = {"error": "Something went wrong, try again, don't screw up this time!"}
    return render(request, "login_app/password_reset_form.html", context)

login_app/templates/login_app/login.html
{% extends 'bank_app/base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
<h1>Login</h1>
<hr>
<form action="{% url 'login_app:login' %}" method="POST">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <input class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
        </div>
    </div>
</form>
<hr>
{% if error %}<p style="color:red">{{error}}</p> {% endif %}
<a href="{% url 'login_app:password_reset' %}">Request Password Reset</a>
<hr>
<div>
    <p> <b> Hello,</b>
        This is Miklas' and davids bank project.
    </p>
    <p>
        <b>Banker:</b><br>
        Banker username: bankmand <br>
        Banker password: asd123
    </p>
    <p>
        <b>Customer with gold rank:</b><br>
        Customer username: testuser <br>
        Customer password: test123
    </p>
    <p>
        <b>Customer with Basic rank:</b><br>
        Customer username: testuser2 <br>
        Customer password: test123
    </p>
    <p>
        Only for backend <br>
        Admin username: admin <br>
        Admin password: admin
    </p>
</div>
{% endblock %}

login_app/templates/login_app/password_reset.html
{% extends 'bank_app/base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
    <h1>Request Password Request</h1>
    <hr>
    <form action="{% url 'login_app:password_reset' %}" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email">
                </div>    
                <input class="btn btn-primary" type="submit" value="Reset password">
            </div>
        </div>
    </form>
    <hr>
    {% if message %}{{ message }}{% endif %}
{% endblock %}

login_app/templates/login_app/password_reset_form.html
{% extends 'bank_app/base.html' %}
{% block title %} Login {% endblock %}

{% block content %}
    <h1>New Password</h1>
    <hr />
    <form action="{% url 'login_app:password_reset_form' %}" method="POST">
        <input type="hidden" name="secret" value="{{ secret }}">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <input class="form-control" type="email" name="email" placeholder="Email Address">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="password" placeholder="New Password">
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" name="confirm_password" placeholder="Confirm New Password">
                </div>
                <input class="btn btn-primary" type="submit" value="Set New Password">
            </div>
        </div>
    </form>
    <hr />
    {% if error %}{{ error }}{% endif %}
{% endblock %}